### ISSUE TITLE
Tesselating block model error

### ISSUE THREAD

**Issue by Timolino456** [Snownee/SnowRealMagic#54] opened 2020-02-19 18:49 UTC
Yesterday I was building the roof of my small house using oak stairs. Everything was fine and when placing another one, it crashed. I'm not an expert but the crash report lets me guess that the error is caused by this mod. Using a different version of the mod didn't help. Uninstalling the mod and opening a copy of the world didn't work either.

The crash report I got when trying to open it with the latest 1.14.4 version of the mod:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 19.02.20 19:43
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at snownee.kiwi.client.model.TextureModel.getQuads(TextureModel.java:269) ~[?:2.6.3] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:137) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:88) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:95) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:89) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
	at mods.octarinecore.client.render.RenderCtx.render(BlockContext.kt:69) ~[?:2.5.0] {re:classloading}
	at mods.octarinecore.client.render.CombinedContext.render(CombinedContext.kt:30) ~[?:2.5.0] {re:classloading}
	at mods.octarinecore.client.render.CombinedContext.render$default(CombinedContext.kt:28) ~[?:2.5.0] {re:classloading}
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:102) ~[?:2.5.0] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRender.redirect$zzc000$renderBlock(ChunkRender.java:1015) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRender.func_178581_b(ChunkRender.java:385) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:90) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:39) ~[?:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at snownee.kiwi.client.model.TextureModel.getQuads(TextureModel.java:269)
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:137)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:88)

-- Block model being tesselated --
Details:
	Block: Block{snowrealmagic:stairs}[facing=east,half=bottom,shape=straight,waterlogged=false]
	Block location: World: (-211,119,575), Chunk: (at 13,7,15 in -14,35; contains blocks -224,0,560 to -209,255,575), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:95)

-- Block being tesselated --
Details:
	Block: Block{snowrealmagic:stairs}[facing=east,half=bottom,shape=straight,waterlogged=false]
	Block location: World: (-211,119,575), Chunk: (at 13,7,15 in -14,35; contains blocks -224,0,560 to -209,255,575), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderBlock(BlockRendererDispatcher.java:89)
	at mods.octarinecore.client.render.RenderCtx.render(BlockContext.kt:69)
	at mods.octarinecore.client.render.CombinedContext.render(CombinedContext.kt:30)
	at mods.octarinecore.client.render.CombinedContext.render$default(CombinedContext.kt:28)
	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:102)
	at net.minecraft.client.renderer.chunk.ChunkRender.redirect$zzc000$renderBlock(ChunkRender.java:1015)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Timolino456'/205, l='MpServer', x=-211.23, y=119.00, z=575.10]]
	Chunk stats: Client Chunk Cache: 1089, 729
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 09 - ALPHA, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (228,66,-256), Chunk: (at 4,4,0 in 14,-16; contains blocks 224,0,-256 to 239,255,-241), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1307478 game time, 1538704 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:574)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:45)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1727057712 bytes (1647 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.2.0.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.0.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.0.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.0.jar mixinbootstrap PLUGINSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.0
	FML Language Providers: 
		javafml@28.2
		minecraft@1
		kotlinfml@1.4.0
	Mod List: 
		forge-1.14.4-28.2.0-client.jar Minecraft {minecraft@1.14.4 DONE}
		SoundControl-1.14.4-0.0.5.0.jar §3Dynamic Surroundings
§eSound Control {sndctrl@1.14.4-0.0.5.0 DONE}
		Environs-1.14.4-0.0.5.0.jar §3Dynamic Surroundings
§eEnvirons {environs@1.14.4-0.0.5.0 DONE}
		MouseTweaks-2.12-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.12 DONE}
		UndergroundBiomes-1.14.4-1.0-53.jar Underground Biomes {undergroundbiomes@1.0-53 DONE}
		GoodSkeletonsDontStrafe-v1.1.2-1.14.4.jar Good Skeletons Don't Strafe {goodskeletonsdontstrafe@1.1.2 DONE}
		pamhc2crops-1.14.4-1.0.2.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		toughnessbar-4.1.jar Toughness Bar {toughnessbar@4.1 DONE}
		betaplus-0.5f.jar Beta+ {betaplus@0.5f DONE}
		jei-1.14.4-6.0.0.26.jar Just Enough Items {jei@6.0.0.26 DONE}
		enchantable-1.1.0-mc1.14.4.jar Enchantable {enchantable@1.1.0 DONE}
		AttributeFix-1.14.4-3.0.2.jar AttributeFix {attributefix@3.0.2 DONE}
		MobEffects-1.14.4-0.0.5.0.jar §3Dynamic Surroundings
§eMob Effects {mobeffects@1.14.4-0.0.5.0 DONE}
		BowInfinityFix-1.14.4-rv7.1.jar Bow Infinity Fix {bowinfinityfix@rv7.1 DONE}
		SpartanShields-1.14.4-2.0.0.jar Spartan Shields {spartanshields@2.0.0 DONE}
		Mantle-1.14.4-1.4.32.jar Mantle {mantle@1.4.32 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		FastWorkbench-1.14.4-2.1.4.jar FastWorkbench {fastbench@2.1.4 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		SereneSeasons-1.14.4-2.0.0.14-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.14 DONE}
		backpacked-1.2.0-mc1.14.4.jar Backpacked {backpacked@1.2.0 DONE}
		randompatches-1.14.4-1.21.0.0.jar RandomPatches {randompatches@1.14.4-1.21.0.0 DONE}
		FastFurnace-1.14.4-2.2.4.jar FastFurnace {fastfurnace@2.2.4 DONE}
		AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 DONE}
		SnowRealMagic-1.14.4-1.5.2.jar Snow! Real Magic! {snowrealmagic@1.5.2 DONE}
		Kiwi-1.14.4-2.6.3.jar Kiwi {kiwi@2.6.3 DONE}
		traverse-1.14.4-2.0.3.jar Traverse {traverse@1.14.4-2.0.3 DONE}
		FpsReducer-mc1.14.4-1.13.jar FPS Reducer {fpsreducer@mc1.14.4-1.13 DONE}
		JustEnoughResources-1.14.4-0.10.0.70.jar Just Enough Resources {jeresources@0.10.0.70 DONE}
		BetterThanMending-1.3.2.jar BetterThanMending {betterthanmending@1.3.2 DONE}
		forge-1.14.4-28.2.0-universal.jar Forge {forge@28.2.0 DONE}
		Quark-r2.0-210.jar Quark {quark@r2.0-210 DONE}
		Aquaculture-1.14.4-2.0.3.jar Aquaculture 2 {aquaculture@1.14.4-2.0.3 DONE}
		mysticallib-1.14.4-1.13.0.jar Mystical Lib {mysticallib@1.14.4-1.13.0 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		overloadedarmorbar-3.0.0b.jar Overloaded Armor Bar {overloadedarmorbar@3.0.0b DONE}
		BetterFoliage-2.5.0-Forge-1.14.4.jar Better Foliage {betterfoliage@2.5.0 DONE}
		BetterAdvancements-1.14.4-0.1.0.90.jar Better Advancements {betteradvancements@0.1.0.90 DONE}
	Kiwi Modules: 
		kiwi:contributors
		snowrealmagic:snowrealmagic
	Launched Version: 1.14.4-forge-28.2.0
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources, vanilla, file/NewDefault+v1.25[MC1.13-1.14.4].zip, file/Toxs Vision [Beta v1.0].zip, file/Nate's+Tweaks+0.24+1.14.zip, file/Improved Chicken Model.zip, file/Kartixx's OAS Pack 1.14.4.zip, file/Shield+Corrections+§7[Regular].zip, file/Consistency-1.1.0.zip, file/Inconsistency-1.1.0.zip, mod:undergroundbiomesores
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor 
	OptiFine Version: OptiFine_1.14.4_HD_U_F5
	OptiFine Build: 20191204-141250
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Kappa_v2.0.zip
	OpenGlVersion: 4.6.0 NVIDIA 441.87
	OpenGlRenderer: GeForce RTX 2070 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by Snownee** [comment] 2020-02-19 19:03
Duplicate of #52

**Closed as completed by Snownee** 2020-02-19 19:03 UTC
Labels: duplicate
