### ISSUE TITLE
Grass Blocks doesn't change its model with snow covered flowers

### ISSUE THREAD

**Issue by WenXin20** [Snownee/SnowRealMagic#46] opened 2020-01-17 23:24 UTC
* Forge Version: 28.1.115
 * Mod Version: 1.5.2
 * Have OptiFine installed? Yes

Grass blocks doesn't change the property to `snowy:true`, so its model doesn't change to the snowy variant if a flower block contains snow above it, which can make hillsides look inconsistent.

**Comment by Snownee** [comment] 2020-01-18 07:39
Duplicate of #39. Only if Forge fixes this bug can I re-add this feature

**Closed as completed by Snownee** 2020-01-18 07:39 UTC
Labels: duplicate
