### ISSUE TITLE
Incompatibility with Moonlight Lib

### ISSUE THREAD

**Issue by Typhonidite** [Snownee/SnowRealMagic#258] opened 2023-01-27 04:20 UTC
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

Any (6.2.2)

### Modloader version

Forge 43.2.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Typhonidite/d3caf6f17cc027f0f4739dafbe60132c

### Issue description

The mod is incompatible with Moonlight Library, even with the latest versions of both Snow! Real Magic! and Kiwi.

**Comment by Snownee** [comment] 2023-01-27 04:22
Hello, I can't reproduce this issue

**Comment by Typhonidite** [comment] 2023-01-27 04:52
Huh? That's... I'm not sure I understand, then.
Can you tell anything obviously wrong within the logs? Or what could be causing the issue, exactly, if not an incompatibility between the two?

**Comment by Snownee** [comment] 2023-03-12 04:37
Duplicate of #269

**Closed as not planned by Snownee** 2023-03-12 04:37 UTC
