### ISSUE TITLE
Snow Real Magic Crashing cause of Mod Compat

### ISSUE THREAD

**Issue by ModernGamingWorld** [Snownee/SnowRealMagic#223] opened 2022-09-08 22:32 UTC
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

SnowRealMagic-1.19.2-forge-5.0.2.jar

### Modloader version

Forge: 43.1.16

### Modpack info

https://www.curseforge.com/minecraft/modpacks/monumental-experience/files/3973643

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/ModernGamingWorld/56c738f01126c08ecff8805c28779dd5

### Issue description

I am currently using Snow Real magic in the pack I listed above, but after Updating Kiwi, Spice of Life, Rubidium, Minecolonies, and Ambient Sounds, That Snow Real Magic Crashes. I think it has to do with your mod not like Rubidium, but from what I understand it should work no problems

**Comment by ModernGamingWorld** [comment] 2022-09-08 23:15
Update Disabling Kiwi/Snow Real Magic Resolve the crash, so its an issue with this mod

**Comment by Snownee** [comment] 2022-09-09 05:20
Duplicate of #222

**Closed as not planned by Snownee** 2022-09-09 05:20 UTC

**Comment by ModernGamingWorld** [comment] 2022-09-09 05:43
How is this fixed, if I am using the latest version and its still crashing
