### ISSUE TITLE
Invisible non-solid blocks [1.20.1]

### ISSUE THREAD

**Issue by mpustovoi** [Snownee/SnowRealMagic#317] opened 2023-10-07 15:08 UTC
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

9.0.1

### Modloader version

Fabric: Loader 0.14.22 + API 0.89.3

### Modpack info

https://modrinth.com/modpack/fabulously-optimized

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/mpustovoi/d1b8a53a342564c1ae514cac09d2f9ae

### Issue description

Non-solid blocks (stairs, slabs, fences, grass, tall grass) are invisible when covered with snow.
![huge_2023-10-07_17 55 48](https://github.com/Snownee/SnowRealMagic/assets/92390626/a8ff9c19-b1e5-4904-8c82-1e36c83ac9c0)
**Fabulously Optimized**: 5.4.0 for 1.20.1
Included related mods:
• **Indium** 1.0.27
• **Iris** 1.6.9
• **Sodium** 0.5.3
Libraries:
• **Cloth Config** 11.1.106
• **Kiwi** 1.11.1
Shaders (doesn't matter, cause problem is present without shaders too):
• **Complementary Reimagined** 5.0.1

When using only **Sodium**, **Indium**, **SnowRealMagic** and **Kiwi**, there is no such a problem.

**Comment by Truflacz** [comment] 2023-10-30 00:02
ive tested it today with Fabulously Optimized modpack, and this bug happens because of modern fix, if you uncheck the first option in that mod it should be fixed. (atleast it helped me with invisible stairs)

**Comment by Snownee** [comment] 2023-11-09 08:32
Duplicate of #321

**Closed as not planned by Snownee** 2023-11-09 08:32 UTC
