### ISSUE TITLE
Snow accumulation does not work with Serene Seasons

### ISSUE THREAD

**Issue by ThomasC03** [Snownee/SnowRealMagic#75] opened 2020-06-26 23:23 UTC
- Forge 31.2.27
- Minecraft 1.15.2
-SnowRealMagic 1.7.5

When playing with the Serene Seasons mod, the snow will not accumulate.

**Comment by Snownee** [comment] 2020-06-30 18:52
Duplicate of #68

**Closed as completed by Snownee** 2020-06-30 18:52 UTC
