### ISSUE TITLE
1.16 version still crashes with rubidium / embeddium when joining world

### ISSUE THREAD

**Issue by drag0n1zed** [Snownee/SnowRealMagic#325] opened 2023-11-18 14:48 UTC
### Mod loader

Fabric

### Minecraft version

1.16.5

### Mod version

2.9.0

### Modloader version

Forge 36.2.39

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/drag0n1zed/70bb31b6134e68f9b4c19935c290c920

### Issue description

1.16.5 version of the mod still crashes due to incompatibility when loaded with the latest version of rubidium or embeddium.
There's 
[fix: Incompatibility crash with Rubidium v0.7.1 (#314)](https://github.com/Snownee/SnowRealMagic/commit/d6ea96f5a2eefc4bf25f233417e33f1e0690eef2)
and
[fix: #315](https://github.com/Snownee/SnowRealMagic/commit/8f2016a041b13965b2e804ee43a502d4c8a231de)
but there is none for the 1.16 version.

**Comment by qznfbnj** [comment] 2023-11-18 15:49
你可能把模组加载器填错了，是Forge吧？
You may have filled in the wrong mod loader, is it Forge?

这个模组的1.16早停更两年了。你有试过[土豆版](https://www.mcmod.cn/class/9470.html)吗？
The 1.16 version of this mod has been discontinued a long time ago (Jan 3, 2022). Have you tried [Potato Edition](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic-potato-edition)?

**Comment by Snownee** [comment] 2023-11-18 17:44
Duplicate of #225

**Closed as not planned by Snownee** 2023-11-18 17:44 UTC
