### ISSUE TITLE
Bugs out with Macaws Fences and Diagional Fences mod

### ISSUE THREAD

**Issue by JustFoolery** [Snownee/SnowRealMagic#387] opened 2024-08-23 08:20 UTC
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

10.4.4

### Modloader version

Forge: 47.2.17

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://gist.github.com/JustFoolery/522836d8274f5909915de168eb17d16a

### Issue description

Bug with Snow Real Magic, Diagonal Fences, and Macaws Fences mods
When snow covers the fences it will disconnect diagonal fences and disconnect Macaws fences completely.

![2024-08-23_04 10 18](https://github.com/user-attachments/assets/237cfdbd-7c2c-4635-add6-9e836a546a3f)
![2024-08-23_04 08 58](https://github.com/user-attachments/assets/81cb6733-987a-4bf9-ba70-953626cbc830)
![2024-08-23_04 09 40](https://github.com/user-attachments/assets/5eabc8a7-8c13-486c-8acc-6d9240c4ab8b)

**Comment by mpustovoi** [comment] 2024-09-17 16:02
Yes, I also have problem on 1.20.1 and 1.21.
I have problems with these Diagonal <something> all the time. From launching issues to random crashes mid game, so I removed them.
This is probably because diagonality violates the basic rules of Minecraft, idk.

**Comment by Snownee** [comment] 2024-10-08 03:30
Duplicate of #301 and #367

**Closed as not planned by Snownee** 2024-10-08 03:30 UTC
