### ISSUE TITLE
{1.16.5] Macaw's fences and walls, wired fences get replaced

### ISSUE THREAD

**Issue by HMK3** [Snownee/SnowRealMagic#138] opened 2021-08-14 16:47 UTC
If bug: The Wired fences of the macaws mod gets replaced with regular snowed fences, erasing the unique traits of the wired fence, like damage on contact and the ability to destroy items. when the snow melts, the fence returns to normal.
 It's a way to disable certain blocks by the config?

A recreation: [Youtube](https://www.youtube.com/watch?v=9vpxftdwckY)

 * Forge Version: 36.2.0
 * Mod Version: 2.5.8
 * Can you reproduce this issue with relevant mods only?: yes

** Bug reports please follow the format! or it might be closed! **

**Comment by Snownee** [comment] 2023-12-21 13:58
Duplicate of #301

**Closed as not planned by Snownee** 2023-12-21 13:58 UTC
Labels: enhancement, cross-mod
