### ISSUE TITLE
Snow! Real Magic! Mod Crashing game on World Startup.

### ISSUE THREAD

**Issue by alexia8225** [Snownee/SnowRealMagic#386] opened 2024-08-10 02:07 UTC
### Mod loader

Fabric

### Minecraft version

1.21

### Mod version

[Fabric 1.21] 11.0.2

### Modloader version

Fabric Loader: 0.16.0 / Fabric Api: 0.102.0

### Modpack info

No

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

<script src="https://gist.github.com/alexia8225/4194a2619ed83f0dafca280215f54218.js"></script>

### Issue description

Hello! Snow! Real Magic! is a great mod and I've liked it since I've gotten it, but since yesterday my world crashes the game every time I load it up. I also tried it on a new world, and in a new world on Prism Launcher with just the mod installed and it crashes. I know Optifine isn't compatible so I deleted all Optifine files off my computer so from what I know it shouldn't be in my game anymore and it still is crashing with Optifine uninstalled. The game works with Snow! Real Magic! uninstalled but I was hoping I didn't have to get rid of it since I've had it for a few weeks now and quite like it along with SereneSeasons. I had to reach out for help because I couldn't find a resolution anywhere else on the internet so bare with me please this is my first time doing this lol. Thank you :)

**Comment by Snownee** [comment] 2024-08-10 02:27
Duplicate of #385

**Closed as not planned by Snownee** 2024-08-10 02:27 UTC

**Comment by alexia8225** [comment] 2024-08-10 22:56
I've been trying to fix this issue since yesterday and although it is a bug with Indium I've downgraded to Indium 1.0.33, Snow! Real Magic! 11.0.0 and Sodium 0.5.9 all for Minecraft version 1.21 and still crashing on startup. There are also gray patches of grass in my survival world now that I've had to take out the mod. Thank you
