### ISSUE TITLE
[Feature Request] Support for Immersive Weathering mod

### ISSUE THREAD

**Issue by DarkShadow44** [Snownee/SnowRealMagic#211] opened 2022-06-20 21:21 UTC
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.1.0

### Modloader version

40.1.51

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

[Immersive Weathering](https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-forge) generates fallen leaves, would be nice to have snow variants for those.

**Comment by Snownee** [comment] 2022-11-04 18:20
Duplicate of #234

**Closed as completed by Snownee** 2022-11-04 18:20 UTC
