### ISSUE TITLE
Collision issue with cryosol block (Immersive Weathering)

### ISSUE THREAD

**Issue by AlonsoCid** [Snownee/SnowRealMagic#298] opened 2023-06-28 10:38 UTC
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

5.1.0

### Modloader version

Fabric: Loader 0.14.21 + API 0.76.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

<script src="https://gist.github.com/AlonsoCid/ef11a74cd341f3f535717436084532f0.js"></script>

### Issue description

When snow is placed on a cryosol block (from the mod Immersive Weathering), it is placed inside the block as if it wasn’t there. This is especially an issue since cryosol substitutes almost all dirt blocks in snow biomes. I have tested it and it happened even with only those 2 mods installed. I don’t know if the problem is in your mod or in the other, but I would appreciate it if you could take a look and fix it.

Immersive Weathering web: https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-fabric

**Comment by Snownee** [comment] 2023-06-28 10:41
Duplicate of https://github.com/Snownee/SnowRealMagic/issues/281

**Closed as not planned by Snownee** 2023-06-28 10:41 UTC
