### ISSUE TITLE
Incompatibility with Immersive Weathering (block cryosol)

### ISSUE THREAD

**Issue by matzar24** [Snownee/SnowRealMagic#294] opened 2023-06-15 15:24 UTC
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

6.5.1

### Modloader version

43.2.0 recomended 1.19.2

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

https://github.com/Snownee/SnowRealMagic/assets/47837757/cdaaca19-a702-43af-9d0c-163f5c1dd782

![2023-06-15_17 18 14](https://github.com/Snownee/SnowRealMagic/assets/47837757/541c2e3b-171f-41cb-bfe7-2f11bb619dac)

**Comment by Snownee** [comment] 2023-06-15 15:30
Duplicate of #281

**Closed as not planned by Snownee** 2023-06-15 15:30 UTC
