### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Redgi110** [Snownee/SnowRealMagic#257] opened 2023-01-26 18:10 UTC
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

6.0.0 and above

### Modloader version

Forge 43.2.3

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

[22:08:41] [main/INFO]: ModLauncher running: args [--username, Redgi, --version, ForgeOptiFine 1.19.2, --gameDir, C:\Users\ASUS\AppData\Roaming\.minecraft, --assetsDir, C:\Users\ASUS\AppData\Roaming\.minecraft\assets, --assetIndex, 1.19, --uuid, 7e847dc5-831c-11e8-91b8-002590a1379b, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, modified, --width, 925, --height, 530, --launchTarget, forgeclient, --fml.forgeVersion, 43.2.3, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853] [22:08:41] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0 [22:08:41] [main/INFO]: OptiFineTransformationService.onLoad [22:08:41] [main/INFO]: OptiFine ZIP file URL: union:/C:/Users/ASUS/AppData/Roaming/.minecraft/mods/OptiFine-OptiFine-1.19.2_HD_U_I1_pre4.jar%23149!/ [22:08:41] [main/INFO]: OptiFine ZIP file: C:\Users\ASUS\AppData\Roaming\.minecraft\mods\OptiFine-OptiFine-1.19.2_HD_U_I1_pre4.jar [22:08:41] [main/INFO]: Target.PRE_CLASS is available [22:08:41] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/ASUS/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2391!/ Service=ModLauncher Env=CLIENT [22:08:41] [main/INFO]: OptiFineTransformationService.initialize [22:08:41] [main/INFO]: Found mod file Kiwi-1.19.1-forge-8.1.3.jar of type MOD with provider {mods folder locator at C:\Users\ASUS\AppData\Roaming\.minecraft\mods} [22:08:41] [main/INFO]: Found mod file SnowRealMagic-1.19.2-forge-6.2.2.jar of type MOD with provider {mods folder locator at C:\Users\ASUS\AppData\Roaming\.minecraft\mods} [22:08:41] [main/INFO]: Found mod file tl_skin_cape_forge_1.19_1.19.2-1.28.jar of type MOD with provider {mods folder locator at C:\Users\ASUS\AppData\Roaming\.minecraft\mods} [22:08:41] [main/WARN]: Mod file C:\Users\ASUS\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.19.2-43.2.3\fmlcore-1.19.2-43.2.3.jar is missing mods.toml file [22:08:41] [main/WARN]: Mod file C:\Users\ASUS\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19.2-43.2.3\javafmllanguage-1.19.2-43.2.3.jar is missing mods.toml file [22:08:41] [main/WARN]: Mod file C:\Users\ASUS\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19.2-43.2.3\lowcodelanguage-1.19.2-43.2.3.jar is missing mods.toml file [22:08:41] [main/WARN]: Mod file C:\Users\ASUS\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.19.2-43.2.3\mclanguage-1.19.2-43.2.3.jar is missing mods.toml file [22:08:41] [main/INFO]: Found mod file fmlcore-1.19.2-43.2.3.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2fb5fe30 [22:08:41] [main/INFO]: Found mod file javafmllanguage-1.19.2-43.2.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2fb5fe30 [22:08:41] [main/INFO]: Found mod file lowcodelanguage-1.19.2-43.2.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2fb5fe30 [22:08:41] [main/INFO]: Found mod file mclanguage-1.19.2-43.2.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2fb5fe30 [22:08:41] [main/INFO]: Found mod file client-1.19.2-20220805.130853-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2fb5fe30 [22:08:41] [main/INFO]: Found mod file forge-1.19.2-43.2.3-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2fb5fe30 [22:08:41] [main/INFO]: No dependencies to load found. Skipping! [22:08:42] [main/INFO]: OptiFineTransformationService.transformers [22:08:42] [main/INFO]: Targets: 386 [22:08:42] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.] [22:08:43] [main/INFO]: Successfully loaded Mixin Connector [org.tlauncher.MixinConnector] [22:08:43] [main/INFO]: Launching target 'forgeclient' with arguments [--version, ForgeOptiFine 1.19.2, --gameDir, C:\Users\ASUS\AppData\Roaming\.minecraft, --assetsDir, C:\Users\ASUS\AppData\Roaming\.minecraft\assets, --uuid, 7e847dc5-831c-11e8-91b8-002590a1379b, --username, Redgi, --assetIndex, 1.19, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, modified, --width, 925, --height, 530] [22:08:43] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/pipeline/BlockRenderer (java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer) [22:08:43] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer was not found snowrealmagic.mixins.json:sodium.BlockRendererAccess [22:08:43] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/pipeline/BlockRenderer (java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer) [22:08:43] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer was not found snowrealmagic.mixins.json:sodium.BlockRendererMixin [22:08:43] [main/WARN]: Error loading class: sereneseasons/handler/season/RandomUpdateHandler (java.lang.ClassNotFoundException: sereneseasons.handler.season.RandomUpdateHandler) [22:08:43] [main/WARN]: @Mixin target sereneseasons.handler.season.RandomUpdateHandler was not found snowrealmagic.mixins.json:sereneseasons.RandomUpdateHandlerMixin [22:08:44] [main/FATAL]: Mixin apply failed snowrealmagic.mixins.json:BlockRenderDispatcherMixin -> net.minecraft.client.renderer.block.BlockRenderDispatcher: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on srm_renderBatched could not find any targets matching 'renderBatched(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/BlockAndTintGetter;Lcom/mojang/blaze3d/vertex/PoseStack;Lcom/mojang/blaze3d/vertex/VertexConsumer;ZLnet/minecraft/util/RandomSource;Lnet/minecraftforge/client/model/data/ModelData;Lnet/minecraft/client/renderer/RenderType;Z)V' in net.minecraft.client.renderer.block.BlockRenderDispatcher. Using refmap snowrealmagic.refmap.json [PREINJECT Applicator Phase -> snowrealmagic.mixins.json:BlockRenderDispatcherMixin -> Prepare Injections ->  -> handler$zzm000$srm_renderBatched(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/BlockAndTintGetter;Lcom/mojang/blaze3d/vertex/PoseStack;Lcom/mojang/blaze3d/vertex/VertexConsumer;ZLnet/minecraft/util/RandomSource;Lnet/minecraftforge/client/model/data/ModelData;Lnet/minecraft/client/renderer/RenderType;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse] org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on srm_renderBatched could not find any targets matching 'renderBatched(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/BlockAndTintGetter;Lcom/mojang/blaze3d/vertex/PoseStack;Lcom/mojang/blaze3d/vertex/VertexConsumer;ZLnet/minecraft/util/RandomSource;Lnet/minecraftforge/client/model/data/ModelData;Lnet/minecraft/client/renderer/RenderType;Z)V' in net.minecraft.client.renderer.block.BlockRenderDispatcher. Using refmap snowrealmagic.refmap.json [PREINJECT Applicator Phase -> snowrealmagic.mixins.json:BlockRenderDispatcherMixin -> Prepare Injections ->  -> handler$zzm000$srm_renderBatched(Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/BlockAndTintGetter;Lcom/mojang/blaze3d/vertex/PoseStack;Lcom/mojang/blaze3d/vertex/VertexConsumer;ZLnet/minecraft/util/RandomSource;Lnet/minecraftforge/client/model/data/ModelData;Lnet/minecraft/client/renderer/RenderType;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] 	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?] 	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?] 	at java.lang.Class.getDeclaredFields(Class.java:2371) ~[?:?] 	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[OptiFine-OptiFine-1.19.2_HD_U_I1_pre4.jar%23159!/:?] 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) ~[OptiFine-OptiFine-1.19.2_HD_U_I1_pre4.jar%23159!/:?] 	at net.minecraft.CrashReport.m_127526_(CrashReport.java:175) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?] 	at net.minecraft.CrashReport.m_127529_(CrashReport.java:345) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?] 	at net.minecraft.client.main.Main.m_239872_(Main.java:144) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?] 	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23153!/:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.3.jar%2395!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]

### Issue description

Crash on start if version 6.0 and above.

**Comment by Snownee** [comment] 2023-03-12 05:35
Duplicate of #269

**Closed as not planned by Snownee** 2023-03-12 05:35 UTC
